SITE_LOGO = "/assets/img/atxcf_logo_small.jpg"
AVATAR = "/assets/img/atxcf_logo_small.jpg"
CARD_IMAGE = "/assets/img/20200126_atxcf_bg_sq-1.png"
HEADER_IMAGE = "/assets/img/20200126_atxcf_bg_sq-1.png"
PASSWORD_SPECIAL_SYMBOLS = "$@#%"
PASSWORD_MINIMUM_LENGTH = 8
PASSWORD_MAXIMUM_LENGTH = 64
PASSWORD_SPECIAL_SYMBOLS_ENABLED = 1
PASSWORD_MINIMUM_LENGTH_ENABLED = 1
PASSWORD_MAXIMUM_LENGTH_ENABLED = 1
PASSWORD_DIGIT_ENABLED = 1
PASSWORD_UPPER_ENABLED = 1
PASSWORD_LOWER_ENABLED = 1
EMAIL_VALIDATE_DELIVERABILITY_ENABLED = 1

DEFAULT_JWT_ALGORITHM = "HS256"

CORS_ORIGINS = ["http://localhost", "http://localhost:8080"]
