"""adding post_time column to HashTag

Revision ID: 0370fd78eac0
Revises: 9655ba7bf1f8
Create Date: 2023-03-29 14:39:08.870785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0370fd78eac0'
down_revision = '9655ba7bf1f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hash_tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hash_tag', schema=None) as batch_op:
        batch_op.drop_column('post_time')

    # ### end Alembic commands ###
