"""adding GlobalSettings

Revision ID: 07370befc489
Revises: 59fe19bdec1f
Create Date: 2024-07-08 22:54:35.392058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07370befc489'
down_revision = '59fe19bdec1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('var', sa.String(length=128), nullable=True),
    sa.Column('val', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('var')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_settings')
    # ### end Alembic commands ###
