"""adding created and modified time columns

Revision ID: 15f470aeceb6
Revises: 0bde778905e4
Create Date: 2023-03-20 21:00:01.122848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f470aeceb6'
down_revision = '0bde778905e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modified_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('modified_time')
        batch_op.drop_column('created_time')

    # ### end Alembic commands ###
