"""adding header text field to user object

Revision ID: 1ac73ff24627
Revises: d1ad681bb005
Create Date: 2023-03-21 20:48:18.293952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac73ff24627'
down_revision = 'd1ad681bb005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('header_text', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('header_text')

    # ### end Alembic commands ###
