"""adding post view count

Revision ID: 1f6f573e1e0e
Revises: 75a3fb8358eb
Create Date: 2023-04-24 16:06:17.501692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6f573e1e0e'
down_revision = '75a3fb8358eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posted_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posted_message', schema=None) as batch_op:
        batch_op.drop_column('view_count')

    # ### end Alembic commands ###
