"""increasing password column size and using 2^n sizes for fields

Revision ID: 59fe19bdec1f
Revises: 3ea6dd022766
Create Date: 2023-11-14 01:41:39.971365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59fe19bdec1f'
down_revision = '3ea6dd022766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1024),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=1024),
               existing_nullable=True)
        batch_op.alter_column('avatar_url',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=1024),
               existing_nullable=True)
        batch_op.alter_column('header_image_url',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=1024),
               existing_nullable=True)
        batch_op.alter_column('card_image_url',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=1024),
               existing_nullable=True)
        batch_op.alter_column('alternate_email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.String(length=10240),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=10240),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
        batch_op.alter_column('alternate_email',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('card_image_url',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('header_image_url',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('avatar_url',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
