"""adding last_login_addr field to users info

Revision ID: 75a3fb8358eb
Revises: 55f06d74162b
Create Date: 2023-04-24 03:43:58.393691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a3fb8358eb'
down_revision = '55f06d74162b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_addr', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login_addr')

    # ### end Alembic commands ###
