"""adding create/modified/accessed time records for settings

Revision ID: 91de3481129f
Revises: f9ff86a1e957
Create Date: 2024-07-21 02:29:31.867392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91de3481129f'
down_revision = 'f9ff86a1e957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modified_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('accessed_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('accessed_time')
        batch_op.drop_column('modified_time')
        batch_op.drop_column('created_time')

    # ### end Alembic commands ###
