"""adding tables for post reactions, emojis, hash tags, etc.

Revision ID: 9655ba7bf1f8
Revises: 30d704e2e32c
Create Date: 2023-03-24 17:33:15.278923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9655ba7bf1f8'
down_revision = '30d704e2e32c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emoji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('added_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('emoji_url', sa.String(length=1000), nullable=True),
    sa.Column('emoji_description', sa.String(length=1000), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hash_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('reaction_time', sa.DateTime(), nullable=True),
    sa.Column('emoji_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tag_description', sa.String(length=1000), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('last_used_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('posted_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repost_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posted_message', schema=None) as batch_op:
        batch_op.drop_column('deleted')
        batch_op.drop_column('repost_id')

    op.drop_table('tag')
    op.drop_table('reaction')
    op.drop_table('hash_tag')
    op.drop_table('emoji')
    # ### end Alembic commands ###
