"""adding deleted column to Reaction table

Revision ID: a2ccc9829e31
Revises: 0370fd78eac0
Create Date: 2023-03-29 15:40:27.658677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ccc9829e31'
down_revision = '0370fd78eac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
