"""Adding more info to UserChange event

Revision ID: a2fda4a9c527
Revises: e43e41a1ba5b
Create Date: 2023-04-23 22:33:58.388403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2fda4a9c527'
down_revision = 'e43e41a1ba5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_change', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referrer', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('remote_addr', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('endpoint', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_change', schema=None) as batch_op:
        batch_op.drop_column('endpoint')
        batch_op.drop_column('remote_addr')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('referrer')

    # ### end Alembic commands ###
