"""adding more columns to user table

Revision ID: ad6eb5e7134e
Revises: c9bdbd91f28f
Create Date: 2023-03-20 20:21:42.730558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6eb5e7134e'
down_revision = 'c9bdbd91f28f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('header_image_url', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('alternate_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('alternate_email_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('alternate_email_verified')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('alternate_email')
        batch_op.drop_column('header_image_url')
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
