"""adding PostedMessageView

Revision ID: e105d1383e07
Revises: 9a0034cbce27
Create Date: 2023-04-24 17:49:38.626776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e105d1383e07'
down_revision = '9a0034cbce27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posted_message_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('view_time', sa.DateTime(), nullable=True),
    sa.Column('current_user', sa.String(length=256), nullable=True),
    sa.Column('referrer', sa.String(length=256), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('remote_addr', sa.String(length=256), nullable=True),
    sa.Column('endpoint', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posted_message_view')
    # ### end Alembic commands ###
