"""Adding PostedMessage table

Revision ID: e965a9eb310a
Revises: 1ac73ff24627
Create Date: 2023-03-22 15:49:55.611602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e965a9eb310a'
down_revision = '1ac73ff24627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posted_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_time', sa.DateTime(), nullable=True),
    sa.Column('post_content', sa.String(length=1024), nullable=True),
    sa.Column('reply_to', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posted_message')
    # ### end Alembic commands ###
