"""adding parent_id to GlobalSettings records

Revision ID: f9ff86a1e957
Revises: 07370befc489
Create Date: 2024-07-21 01:09:46.570276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ff86a1e957'
down_revision = '07370befc489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_file_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emoji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('added_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('emoji_url', sa.String(length=1000), nullable=True),
    sa.Column('emoji_description', sa.String(length=1000), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('var', sa.String(length=128), nullable=True),
    sa.Column('val', sa.String(length=256), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hash_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('post_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posted_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_time', sa.DateTime(), nullable=True),
    sa.Column('post_content', sa.String(length=1024), nullable=True),
    sa.Column('reply_to', sa.Integer(), nullable=True),
    sa.Column('repost_id', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posted_message_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('view_time', sa.DateTime(), nullable=True),
    sa.Column('current_user', sa.String(length=256), nullable=True),
    sa.Column('referrer', sa.String(length=256), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('remote_addr', sa.String(length=256), nullable=True),
    sa.Column('endpoint', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('reaction_time', sa.DateTime(), nullable=True),
    sa.Column('emoji_id', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_code', sa.Integer(), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('event_desc', sa.String(length=256), nullable=True),
    sa.Column('referrer', sa.String(length=256), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('remote_addr', sa.String(length=256), nullable=True),
    sa.Column('endpoint', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tag_description', sa.String(length=1000), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('last_used_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=1024), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('header_image_url', sa.String(length=1024), nullable=True),
    sa.Column('header_text', sa.String(length=256), nullable=True),
    sa.Column('card_image_url', sa.String(length=1024), nullable=True),
    sa.Column('alternate_email', sa.String(length=128), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('alternate_email_verified', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=10240), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_login_addr', sa.String(length=256), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('post_view_count', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('change_code', sa.Integer(), nullable=True),
    sa.Column('change_time', sa.DateTime(), nullable=True),
    sa.Column('change_desc', sa.String(length=256), nullable=True),
    sa.Column('referrer', sa.String(length=256), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('remote_addr', sa.String(length=256), nullable=True),
    sa.Column('endpoint', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('file_path', sa.String(length=256), nullable=True),
    sa.Column('preview_path', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('preview_path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_file')
    op.drop_table('user_change')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('system_log')
    op.drop_table('reaction')
    op.drop_table('posted_message_view')
    op.drop_table('posted_message')
    op.drop_table('mention')
    op.drop_table('hash_tag')
    op.drop_table('global_settings')
    op.drop_table('emoji')
    op.drop_table('attachment')
    # ### end Alembic commands ###
